### PR TITLE
Prepare for wheel release + populate PyPI page information

### LINKED ISSUE #147: Publish standalone `cuda-core` packages

### PR DESCRIPTION
**Pull request by leofang**
Close #147.

### CODE REVIEW

**Review by vzhurba01 — APPROVED** [review]
LGTM but I do have a general comment. By having both `DESCRIPTION.rst` and README.md`  I feel like we're duplicating some similar documentation and requires us to remember to update both.

I see that the rst version is a simplified to be better suited for a wheel distribution, so I'm ok with this. Just noticing this made me hesitate for a second and I wanted it to be noted.

**Comment by leofang** [comment]
Thanks, Vlad. Indeed we're duplicating some of the information. It might take a few iterations to consolidate the two files and have something presentable on both PyPI and GitHub. Let's address this in the next release.

**Pull request merged**
