### PR TITLE
Add py313 builds

### PR DESCRIPTION
**Pull request by leofang**
~~Blocked by #267.~~

xref: https://github.com/NVIDIA/cuda-python/issues/131#issuecomment-2513358549

### CODE REVIEW

**Comment by leofang** [comment]
Looks like everything builds fine (after a few retries, due to #271).

**Comment by leofang** [comment]
@ksimpson-work thanks for [the earlier suggestion](https://github.com/NVIDIA/cuda-python/pull/267#discussion_r1873871447), this PR is now very clean (one-liner, as expected) 🙂

**Review by ksimpson-work — APPROVED** [review]
nice, thanks !

**Comment by leofang** [comment]
The test CI has been merged (#124). Let's get this actually tested in the CI.

**Comment by leofang** [comment]
All is green, let's merge!

**Pull request merged**
